// AUTO-GENERATED. Run `npm run build:logo` to regenerate.
export const LOGO_DATA_URI = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAAAYCAIAAACKi2/DAAAARklEQVR4nO3QMQ0AMAwEsTAJxAIviTLI0iE/WDoAJ1efq6FaPwgPECBAgAAFBwgQIECAggMECBAgQMEBAgQIEKDgAAH66wEAiEHEx+EIpwAAAABJRU5ErkJggg==';
